version: "3.8"

services:
  jobmanager:
    image: flink:1.18
    container_name: flink-jobmanager
    ports:
      - "8081:8081" # Flink Web UI
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.18.1
    container_name: flink-taskmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        tasmanager.numberOfTaslSots: 2
    depends_on:
      - jobmanager